DROP DATABASE IF EXISTS test_db;
CREATE DATABASE test_db
CHARACTER SET UTF8
COLLATE UTF8_GENERAL_CI;

USE test_db;

DROP USER if EXISTS 'mysql'@'localhost';
CREATE USER 'mysql'@'localhost' IDENTIFIED BY 'mysql';
GRANT ALL PRIVILEGES ON test_db TO 'mysql'@'localhost' IDENTIFIED BY 'mysql' WITH GRANT OPTION;

CREATE TABLE group_t (
id INT(11) PRIMARY KEY AUTO_INCREMENT,
article_id INT(11) NOT NULL,
sequence INT(11) NOT NULL,
value VARCHAR(30) NOT NULL,
type VARCHAR(30) NOT NULL
)
AUTO_INCREMENT = 1
ENGINE = INNODB
AVG_ROW_LENGTH = 5461
CHARACTER SET UTF8
COLLATE UTF8_GENERAL_CI;

CREATE TABLE content (
group_id INT(11) NOT NULL,
sequence INT(11) DEFAULT NULL,
value VARCHAR(100) NOT NULL,
CONSTRAINT fk_con_gro FOREIGN KEY (group_id) REFERENCES
group_t (id)
)
AUTO_INCREMENT = 1
ENGINE = INNODB
AVG_ROW_LENGTH = 5461
CHARACTER SET UTF8
COLLATE UTF8_GENERAL_CI;